### ISSUE TITLE
SMTC 未设置 max_seek_time 和 start_time

### ISSUE THREAD

**Issue by mokurin000** [go-musicfox/go-musicfox#259]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

使用 [`test-gsmtc`](https://github.com/waylyrics/test-gsmtc) 检查 musixfox 的 SMTC 字段

得到输出：
```yaml
    timeline_properties:
        start_time: 0
        end_time: 0
        max_seek_time: 0
        min_seek_time: 0
        position: 21693000000
        last_updated_time: 133599952758105450
```

其中 `end_time` 是 The end timestamp of the current media item.
`min_seek_time` 是 The earliest timestamp at which the current media item can currently seek to.
end_time 应该设为歌曲长度
min_seek_time 为当前歌曲已经可以播放的长度（流获取/解码）

### Environment / 运行环境

Windows 11
版本	10.0.22631 版本 22631
x86_64 i7-12700H

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_
